name: expressions
on:
  workflow_dispatch:
    inputs:
      str1:
        description: "main string"
        required: true
        type: string
      str2:
        description: "substring"
        required: true
        type: string
jobs:
  expressions-main-job:
    if: ${{ contains(inputs.str1, inputs.str2) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "str2 is contained in str1"
      - run: echo ${{ contains(inputs.str1, inputs.str2) }}
