name: hola-mundo
on:
  - push
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup nodejs
        uses: actions/setup-node@v4
      - name: Run hello world
        run: node src/index.js
