name: triggers
on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - stage
      - "release/**"
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
      - name: Run hello world
        run: node src/index.js
